version: "3.7"

services:
  consul-01:
    image: consul:1.15.4
    container_name: consul-01
    hostname: consul-01
    labels:
      - "name=consul-01"
    restart: unless-stopped
    volumes:
      - ./data:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0