##################################################
# spring
##################################################
spring:
  application:
    name: ejetool-admin-spring
  config:
    import:
      - classpath:server.yml
      - classpath:eureka.yml
      - classpath:logger.yml
      - classpath:management.yml
      - classpath:sentry.yml
  security:
    user:
      name: xadmin
      password: xadmin
  boot:
    admin:
      ui:
        remember-me-enabled: false
        #public-url: http://127.0.0.1:9001
        poll-timer:
          logfile: 30000 
      client:
        instance:
          #service-host-type: CANONICAL_HOST_NAME
          #service-url: http://127.0.0.1:9001/sbm
          metadata:
            user:
              name: xadmin
              password: xadmin
        username: xadmin
        password: xadmin
        url: http://localhost:9000/sbm
  # cloud:
  #   gateway:
  #     routes:
  #       - id: auth
  #         uri: http://localhost:8081/
  #         predicates:
  #           - Path=/auth/**
  #       - id: second-service
  #         uri: http://localhost:8085/
  #         predicates:
  #           - Path=/videoai/**
