##################################################
# spring
##################################################
spring:
  application:
    name: ejetool-gateway-api
  config:
    import:
      - classpath:server.yml
      - classpath:eureka.yml
      - classpath:logger.yml
      - classpath:management.yml
      - classpath:sentry.yml
  # boot:
  #   admin:
  #     client:
  #       url:
  #         - http://127.0.0.1:9000/sbm
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: second-service
          uri: http://localhost:8085/
          predicates:
            - Path=/videoai/**
