##################################################
# spring 
##################################################
spring:
  application:
    name: ejetool-videoai-chatbot
  config:
    import:
      - classpath:server.yml
      - classpath:eureka.yml
      - classpath:logger.yml
      - classpath:management.yml
      - classpath:sentry.yml
  jmx:
    enabled: true
  # boot:
  #   admin:
  #     client:
  #       url:
  #         - http://127.0.0.1:9000/sbm

##################################################
# ejetool
##################################################
ejetool:
  host: http://127.0.0.1:8080
  api_key: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq

##################################################
# telegram
##################################################
telegram:
  bot:
    token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    default_chat_id: 1234
    admin_ids: 1234
