##################################################
# spring
##################################################
spring:
  application:
    name: ejetool-account-api
  config:
    import:
      - classpath:server.yml
      - classpath:eureka.yml
      - classpath:logger.yml
      - classpath:management.yml
      - classpath:sentry.yml
      - classpath:openapi.yml
  jpa:
    hibernate:
      # values: none, create, create-drop, update, validate
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  datasource:
    # driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # connectionString
    url: jdbc:mysql://localhost:21101/ejetool-account?useUnicode=true&autoReconnect=true
    username: ejetool-svc
    password: file:../../secrets.fake
  
  data:
    redis:
      host: localhost
      port: 21102


##################################################
# auth
##################################################
auth:
  security:
    secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    issuer: https://www.ejetool.com
    allowed_issuers: ["https://www.ejetool.com"]
    private_key_path: file:./keys/serivce_auth.key
    public_key_path: file:./keys/serivce_auth.pub

##################################################
# Google
##################################################
google: 
  application_name: ejegong-creator-ai
  # Link: https://cloud.google.com/iam/docs/service-account-overview?hl=ko
  service_account: |
    {
      "type": "service_account",
      "project_id": "project_id",
      "private_key_id": "private_key_id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nprivate_key\n-----END PRIVATE KEY-----\n",
      "client_email": "service_account@service_account.iam.gserviceaccount.com",
      "client_id": "1234",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service_account%40service_account.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
