##################################################
# doc
#################################################
openapi:
  server:
    url: http://127.0.0.1:8080

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  # use-fqn: true
  paths-to-match:
    - /contents/**
  api-servers:
    - http://127.0.0.1:8080
  api-docs:
    path: /docs/openapi/${spring.application.name}.json
  swagger-ui:
    path: /docs/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    urls:
      - url: /docs/openapi/${spring.application.name}.json
        name: Account
