##################################################
# spring
##################################################
spring:
  application:
    name: ejetool-videoai-event-consumer
  # boot:
  #   admin:
  #     client:
  #       url:
  #         - http://127.0.0.1:9000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  datasource:
    # driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # connectionString
    url: jdbc:mysql://localhost:21101/ejetool-videoai?useUnicode=true&autoReconnect=true
    username: ejetool-svc
    password: file:../../secrets.fake
  
  data:
    redis:
      host: localhost
      port: 21102

##################################################
# openai
##################################################
openai:
  api_key: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq

##################################################
# Telegram
##################################################
telegram:
  bot:
    token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    default_chat_id: 1234

##################################################
# Useapi
##################################################
useapi:
  api:
    token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
  midjourney:
    discord_token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    discord_server: 1234
    discord_channel: 1234


##################################################
# Google
##################################################
google: 
  # Link: https://cloud.google.com/iam/docs/service-account-overview?hl=ko
  service_account: |
    {
      "type": "service_account",
      "project_id": "project_id",
      "private_key_id": "private_key_id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nprivate_key\n-----END PRIVATE KEY-----\n",
      "client_email": "service_account@service_account.iam.gserviceaccount.com",
      "client_id": "1234",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service_account%40service_account.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }

##################################################
# make
##################################################
make:
  youtube:
    webhook: https://hook.us1.make.com/webhook_id
    api_key: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq

##################################################
# Logger
##################################################
logging:
  level:
    root: info
    com:
      ejetool: info
  file:
    name: ./logs/${spring.application.name}/std.log