##################################################
# spring
##################################################
spring:
  environment: production
  application:
    name: ejetool-videoai-api
  config:
    import:
      - classpath:server.yml
      - classpath:eureka.yml
      - classpath:logger.yml
      - classpath:management.yml
      - classpath:sentry.yml
      - classpath:openapi.yml
  # boot:
  #   admin:
  #     client:
  #       url:
  #         - http://127.0.0.1:9000/sbm
  jpa:
    hibernate:
      # values: none, create, create-drop, update, validate
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # temp:
        #   "[use_jdbc_metadata_defaults]": false
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/ejetool-videoai?useUnicode=true&autoReconnect=true
    username: 
    password: 
  
  data:
    redis:
      host: localhost
      port: 26379

  jackson:
      property-naming-strategy: SNAKE_CASE

##################################################
# auth
##################################################
auth:
  security:
    allowed_issuers: https://www.ejetool.com
    secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    public_key_path: file:./keys/serivce_auth.pub

##################################################
# openai
##################################################
openai:
  api_key: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq

##################################################
# Telegram
##################################################
telegram:
  bot:
    token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    default_chat_id: 1234

##################################################
# Useapi
##################################################
useapi:
  api:
    token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
  midjourney:
    discord_token: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq
    discord_server: 1234
    discord_channel: 1234

##################################################
# Google
##################################################
google: 
  application_name: ejegong-creator-ai
  # Link: https://cloud.google.com/iam/docs/service-account-overview?hl=ko
  service_account: |
    {
      "type": "service_account",
      "project_id": "project_id",
      "private_key_id": "private_key_id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nprivate_key\n-----END PRIVATE KEY-----\n",
      "client_email": "service_account@service_account.iam.gserviceaccount.com",
      "client_id": "1234",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service_account%40service_account.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }