package com.ejetool.lib.useapi.dto.midjourney;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;

/**
 * status : 200
 * {
 *     "jobid": "<jobid>",
 *     "verb": "imagine",
 *     "status": "started",
 *     "created": "2023-09-09T02:04:49.667Z",
 *     "updated": "2023-09-09T02:04:53.490Z",
 *     "prompt": "Steampunk cat",
 *     "discord": "<ABC…secured…xyz>",
 *     "channel": "<Discord channel id>",
 *     "server": "<Discord server id>",
 *     "maxJobs": 3,
 *     "replyUrl": "https://webhook.site/abc",
 *     "replyRef": "<your optional reference id>",
 *     "messageId": "<Discord message id>",
 *     "content": "**Steampunk cat --s 750 --v 5.2** - <@Discord user id> (Waiting to start)",
 *     "timestamp": "2023-09-09T02:04:51.926000+00:00",
 *     "code": 200
 * }
 */
@Getter
public class JobImagineResponse {
    /**
     * 
     */
    private int code;

    /**
     * 
     */
    private String error;

    /**
     * 
     */
    private String errorDetails;

    /**
     * 
     */
    @JsonProperty("jobid")
    private String jobId;

    /**
     * verb
     * {@link JobVerb}
     */
    private String verb;
    
    /**
     * 상태
     * {@link JobStatus}
     */
    private String status;

    /**
     * YYYY-MM-DDTHH:mm:ss.sssZ, IS0 8601, UTC
     */
    private String created;

    /**
     * YYYY-MM-DDTHH:mm:ss.sssZ, IS0 8601, UTC
     */
    private String updated;
    
    private String prompt;

    /**
     * Provided for debugging purposes only, contains the first 3 and the last 3 characters of the original value
     */
    private String discord;

    /**
     * 
     */
    private String channel;

    /**
     * 
     */
    private String server;

    /**
     * 
     */
    private int maxJobs;

    /**
     * 
     */
    private String replyUrl;

    /**
     * 
     */
    private String replyRef;

    /**
     * 
     */
    private String messageId;

    /**
     * Contains message generated by Midjourney reflecting current generation parameters and progress
     */
    private String content;

    /**
     * 
     */
    private String timestamp;

    /**
     * 
     */
    private String executingJobs;

    /**
     * 
     * @param code
     * @param error
     * @param errorDetails
     * @return
     */
    public static JobImagineResponse createError(int code, String error, String errorDetails) {
        var inst = new JobImagineResponse();
        inst.code = code;
        inst.error = error;
        inst.errorDetails = errorDetails;
        return inst;
    }

    public boolean isSucceed(){
        return this.code == 200;
    }
}
