name: Cleanup Docker Images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  # push:
  #   branches: [ master ]
jobs:
  remove-docker-image:
    runs-on: ubuntu-latest
    steps:
    #   - name: Login to GitHub Container Registry with PAT_TOKEN
    #     uses: docker/login-action@v2
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GHCR_WRITE_TOKEN }}
    #   # https://github.com/Chizkiyahu/delete-untagged-ghcr-action
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.GHCR_WRITE_TOKEN }}
          repository: ${{ github.repository }}
          #repository_owner: ${{ github.repository_owner }}
          untagged_only: true
          owner_type: 'user'
          #except_untagged_multiplatform: true
          #package_name: 'ejetool-videoai-api'
     